(in-package meta-web)

(prog1 (defclass update-sql-table-function
                 nil
                 ((description :value-type string :user-name (make-instance 'meta-level:translated-string :en "description" :fr "description" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h "") :choices (list) :visible t :visible-groups 'nil :modifiable nil :modifiable-groups 'nil :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first t :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :medit)
                  (fn-source :value-type string :user-name (make-instance 'meta-level:translated-string :en "source code" :fr "code source" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h "") :choices (list) :visible t :visible-groups 'nil :modifiable nil :modifiable-groups 'nil :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first t :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :medit)
                  (project :value-type project :user-name (make-instance 'meta-level:translated-string :en "project" :fr "projet" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h "") :choices (list) :visible t :visible-groups 'nil :modifiable nil :modifiable-groups 'nil :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first t :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default)
                  (lambda-form :value-type t :user-name (make-instance 'meta-level:translated-string :en "lambda function" :fr "fonction lambda" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h "") :choices (list) :visible nil :visible-groups 'nil :modifiable nil :modifiable-groups 'nil :stored nil :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first t :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default))
                 (:user-name (make-instance 'meta-level:translated-string :en "function for the SQL table update" :fr "fonction de M.A.J. de la table SQL" :de "" :sp "" :it "") :guid 1898742147556227512199664574 :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h "") :functions (list (make-instance 'meta-level::fc-function :name 'perform-class-table-update :user-name (make-instance 'meta-level:translated-string :en "perform the update of the table" :fr "exécuter la mise à jour de la table" :de "" :sp "" :it "") :visible t :visible-groups 'nil :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "" :en-h "" :fr-h "" :de-h "" :sp-h "" :it-h ""))) :visible t :visible-groups 'nil :instanciable t)))




