(in-package "WEBAPP")

(defvar *base-classes-list* '(user base-app))

(defun create-base-classes (store)
  (dolist (class *base-classes-list*)
     (meta::create-class-table store (find-class class))))

(prog1
    (meta-level:defclass user
                         nil
                         ((user-name :value-type string :user-name (make-instance 'meta-level:translated-string :en "User name" :fr "" :de "" :sp "" :it "") :description "The user name used for login" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :choices (list) :visible t :visible-groups 'nil :modifiable nil :modifiable-groups 'nil :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first nil :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn 'nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :process-new-object-fn 'nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default :slot-view-name 'nil)
                          (password :value-type string :user-name (make-instance 'meta-level:translated-string :en "Password" :fr "" :de "" :sp "" :it "") :description "The password (currently SHA1)" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :choices (list) :visible nil :visible-groups '(:dev) :modifiable nil :modifiable-groups 'nil :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first nil :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn 'nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :process-new-object-fn 'nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default :slot-view-name 'nil)
                          (admin-p :value-type boolean :user-name (make-instance 'meta-level:translated-string :en "Administrator" :fr "" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :choices (list) :visible nil :visible-groups '(:admin) :modifiable nil :modifiable-groups '(:admin) :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first nil :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn 'nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :process-new-object-fn 'nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default :slot-view-name 'nil)
                          (dev-p :value-type boolean :user-name (make-instance 'meta-level:translated-string :en "Developer" :fr "" :de "" :sp "" :it "") :description "true if the user is a developer of the app" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :choices (list) :visible nil :visible-groups '(:admin) :modifiable nil :modifiable-groups '(:admin) :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values nil :new-objects-first nil :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn 'nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :process-new-object-fn 'nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default :slot-view-name 'nil))
                         (:user-name (make-instance 'meta-level:translated-string :en "User" :fr "" :de "" :sp "" :it "") :guid 51 :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :functions (list (make-instance 'meta-level::fc-function :name 'change-user-password :user-name (make-instance 'meta-level:translated-string :en "Change password" :fr "" :de "" :sp "" :it "") :visible nil :visible-groups '(:admin :owner) :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-sql "" :html-tag-attributes 'nil :disable-predicate 'nil :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it ""))) :visible t :visible-groups 'nil :instanciable t)))

(prog1 (meta-level:defclass base-app nil ((users :value-type user :user-name (make-instance 'meta-level:translated-string :en "Users" :fr "" :de "" :sp "" :it "") :description "" :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :choices (list) :visible t :visible-groups 'nil :modifiable nil :modifiable-groups '(:admin :dev) :stored t :in-proxy nil :indexed nil :unique nil :null-allowed t :list-of-values t :new-objects-first nil :linked-value nil :modifiable nil :duplicate-value t :make-copy-string nil :get-value-title (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :get-value-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :sql-length 0 :value-to-string-fn 'nil :nb-decimals 0 :void-link-text (make-instance 'meta-level:translated-string :en "" :fr "" :de "" :sp "" :it "") :can-create-new-object nil :create-new-object nil :process-new-object-fn 'nil :get-value-sql "" :html-tag-attributes 'nil :dont-display-null-value nil :view-type :default :slot-view-name 'nil)) (:user-name (make-instance 'meta-level:translated-string :en "Base application object" :fr "" :de "" :sp "" :it "") :guid 52 :object-help (make-instance 'meta-level::object-help :en "" :fr "" :de "" :sp "" :it "") :functions (list) :visible t :visible-groups 'nil :instanciable t)))

