#!/bin/bash
# This is part of uffi program: 
#    http://uffi.med-info.com
#
# Copyright (c) 2002 Kevin M. Rosenberg <kmr@debian.org>

pkg=uffi
dir=/usr/share/common-lisp/source/$pkg

case "$1" in
    install|upgrade|abort-upgrade)
	# Remove any old versions
	test -h $dir && rm $dir 
	rm -rf ${dir}-[0-9\.]*
	;;
    *)
        echo "preinst called with unknown argument '$1'" >&2
	;;
esac

#DEBHELPER#

exit 0
